
version: '3.4'

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs/:/etc/certs/
    ports:
      - 443:443
    networks:
      - spotify
    depends_on:
      - kibana
    restart: always

  worker:
    image: worker:latest
    volumes:
      - ./database:/app/data
    env_file:
      - ./.env
    networks:
      - spotify
    depends_on:
      - elasticsearch  
    restart: always     

  elasticsearch:
    image: spotify_elasticsearch:latest
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - spotify
    restart: always

  kibana:
    image: spotify_kibana:latest
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URI}
      - SERVER_BASEPATH=${KIBANA_BASEPATH}
      - SERVER_HOST=${KIBANA_SERVERHOST}
      - SERVER_NAME=${KIBANA_SERVERNAME}
    networks:
      - spotify
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: always
      
networks:
  spotify:
    driver: bridge
    
volumes:
  database:
  elasticsearch:
